### ISSUE TITLE
./seeta/FaceEngine.h:3:32: fatal error: seeta/FaceDetector.h: No such file or directory

### ISSUE THREAD

**Issue by zyxcambridge** [seetafaceengine/SeetaFace2#1]
./seeta/FaceEngine.h:3:32: fatal error: seeta/FaceDetector.h: No such file or directory

**Comment by zhuyu-cs** [comment]
First, you need compile this project.

**Comment by 2151330** [comment]
I didn't find seeta/FaceDetector.h, seeta/FaceLandmarker.h, seeta/FaceDatabase.h either

**Comment by seetafaceengine** [comment]
1. Compile all libraries sources. Compilation scripts are in `craft`, including linux and windows. This step will gather all headers and libraries to `craft/<platform>/build`.
2. Compile example. Use `Makefile` in Linux, or use `SeetaExample.sln` in windows.

**Comment by vicwer** [comment]
@seetafaceengine 您好，ubuntu18.04环境下，运行craft/platform/build脚本，编译错误，错误位置是pot.h里的std::function，请问你们有遇到这个情况吗，我在CMake加了C++11，还是报同样的错误。

**Comment by Galaxy-yyyyy** [comment]
README.md中
linux 上 example 的编译运行方法：
1. `cd` 到 `example/search` 目录下，执行 `make` 指令；
2. 拷贝模型文件到程序指定的目录下；
3. 执行脚本 `run.sh`。
请问这里的第2步拷贝模型，指的是什么模型

**Comment by seetafaceengine** [comment]
These models:
    人脸检测模块 FaceDetector 模型下载链接：
    MD5 ：E88669E5F1301CA56162DE8AEF1FD5D5
    百度网盘：https://pan.baidu.com/s/1Dt0M6LXeSe4a0Pjyz5ifkg 提取码：fs8r
    Dropbox : https://www.dropbox.com/s/cemt9fl48t5igfh/fd_2_00.dat?dl=0

    面部特征5点定位模块 FaceLandmarker 模型下载链接：
    MD5 ：877A44AA6F07CB3064AD2828F50F261A
    百度网盘：https://pan.baidu.com/s/1MqofXbmTv8MIxnZTDt3h5A 提取码：7861
    Dropbox : https://www.dropbox.com/s/noy8tien1gmw165/pd_2_00_pts5.dat?dl=0

    面部特征81点定位模块 FaceLandmarker 模型下载链接：
    MD5 ：F3F812F01121B5A80384AF3C35211BDD
    百度网盘：https://pan.baidu.com/s/1CCfTGaSg_JSY3cN-R1Myaw 提取码：p8mc
    Dropbox : https://www.dropbox.com/s/v41lmclaxpwow1d/pd_2_00_pts81.dat?dl=0

    人脸特征提取和比对模块 FaceRecognizer 模型下载链接：
    MD5 ：2D637AAD8B1B7AE62154A877EC291C99
    百度网盘：https://pan.baidu.com/s/1y2vh_BHtYftR24V4xwAVWg 提取码：pim2
    Dropbox : https://www.dropbox.com/s/6aslqcokpljha5j/fr_2_10.dat?dl=0

> 
> 
> README.md中
> linux 上 example 的编译运行方法：
> 
>     1. `cd` 到 `example/search` 目录下，执行 `make` 指令；
> 
>     2. 拷贝模型文件到程序指定的目录下；
> 
>     3. 执行脚本 `run.sh`。
>        请问这里的第2步拷贝模型，指的是什么模型

**Comment by seetafaceengine** [comment]
> 
> 
> @seetafaceengine 您好，ubuntu18.04环境下，运行craft/platform/build脚本，编译错误，错误位置是pot.h里的std::function，请问你们有遇到这个情况吗，我在CMake加了C++11，还是报同样的错误。

It may missing "#include <functional>". Add to fix it.

**Comment by seetafaceengine** [comment]
It may missing "#include \<functional\>". Add to fix it.

**Comment by qingfengmingyue** [comment]
在example/search目录下执行make报如下错：
./seeta/Struct_cv.h:3:33: fatal error: opencv2/core/core.hpp: No such file or directory
compilation terminated.
Makefile:22: recipe for target 'example.o' failed
make: *** [example.o] Error 1

**Comment by 2151330** [comment]
I encountered the following problem. Is the reason that the camera cannot be called? How to solve it，tks
![image](https://user-images.githubusercontent.com/41284417/63262087-a3895180-c2b7-11e9-9752-c0fe3c7c9609.png)

**Comment by davidwhl** [comment]
![image](https://user-images.githubusercontent.com/49928687/64097057-c9255900-cd95-11e9-8726-8f74bfebc21a.png)
win10执行cmake --build .时报错，请问如何修复？ @seetafaceengine

**Comment by seetafaceengine** [comment]
该问题即将关闭，遇到的代码编译和运行问题。请更新最新的代码后重试。
