### ISSUE TITLE
ndk-build with error: static_assert failed

### ISSUE THREAD

**Issue by 31434116** [seetafaceengine/SeetaFace2#10]
C:/Users/yoda/AppData/Local/Android/Sdk/ndk-bundle/build//../sources/cxx-stl/llvm-libc++/include\math.h:999:5: error: static_assert failed due to requirement '!(std::is_same<float, __result_type>::value &&
      std::is_same<float, __result_type>::value)' ""
    static_assert((!(std::is_same<_A1, __result_type>::value &&
    ^              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
D:/sources/SeetaFace2/SeetaNet/sources/jni/../src/include_inner/layers\SeetaNetPowerCPU.h:127:28: note: in instantiation of function template specialization 'pow<float, float>' requested here
                val = std::pow<T>( val, m_power );
                           ^
D:/sources/SeetaFace2/SeetaNet/sources/jni/../src/include_inner/layers\SeetaNetPowerCPU.h:10:5: note: in instantiation of member function 'SeetaNetPowerCPU<float>::Process' requested here
    SeetaNetPowerCPU();
    ^
D:/sources/SeetaFace2/SeetaNet/sources/jni/../src/include_inner/SeetaNetCreateLayerDetailCPU.h:193:24: note: in instantiation of member function 'SeetaNetPowerCPU<float>::SeetaNetPowerCPU' requested here
    output_layer = new SeetaNetPowerCPU<DataType>();
                       ^
D:/sources/SeetaFace2/SeetaNet/sources/jni/../src/include_inner\SeetaNetCreateLayerMapCPU.h:50:101: note: in instantiation of function template specialization 'CreatePowerFunctionCPU<float>' requested here
        FunctionMap.insert( std::pair<int32_t, CREATE_NET_PARSEFUNCTION *>( seeta::Enum_PowerLayer, CreatePowerFunctionCPU<DType> ) );
                                                                                                    ^
D:/sources/SeetaFace2/SeetaNet/sources/jni/../src/include_inner\SeetaNetCreateLayerMapCPU.h:71:205: note: in instantiation of member function 'CreateLayerMapCPU<float>::CreateFunctionMap' requested here
  ...std::map<int32_t, int( * )( SeetaNetBaseLayer<float>* &, SeetaNet_LayerParameter &, SeetaNetResource<float>* )> CreateLayerMapCPU<float>::m_parse_function_map = CreateLayerMapCPU<float>::CreateFunctionMa...

**Comment by seetafaceengine** [comment]
it already fixed in commit: [b7f946c6cc3958ef486d514f7d0a50cf70997f20](https://github.com/seetafaceengine/SeetaFace2/commit/b7f946c6cc3958ef486d514f7d0a50cf70997f20).

**Comment by 31434116** [comment]
Sorry, update solved
