### ISSUE TITLE
How many channels does your model support?

### ISSUE THREAD

**Issue by ereate** [seetafaceengine/SeetaFace2#100]
The input image need 3 channels, through your engine code.
 
I hava a test:  modify channel limit to one channel, and suceess to detect, but not to create feature.

Your mode is only support 3 channel to create feature?

I think it best for supporting any channel of inputting image, and make you face engine more powerfully.

**Comment by seetafaceengine** [comment]
Yes, create feature only support 3 channel image. There is no solution for "any channel" as well. Only 1 channel image was extended, as supporting gray image. The gray image has no obvious effect on face detection, but it has obvious influence on face recognition. At last, only BGR 3 channels image supported. Face detection automatically adjusts gray image into three channel (color) image. I hope it will help you.
