### ISSUE TITLE
不知道如何生成“..\..\SeetaNet\sources\build\lib\x64\seetanet2d.lib”

### ISSUE THREAD

**Issue by mingcv** [seetafaceengine/SeetaFace2#14]
在windows下使用cmake+cl编译时报如上错误

**Comment by GangLiCN** [comment]
Cmake + VS 2015编译时几点注意事项:
1)Cmake 执行时不要使用"Nmake makefiles", 100%失败， 编译成VC格式的工程文件是没问题的
cmake .. -G"Visual Studio 14"   -DPLATFORM="x64" -DCONFIGURATION="Release"
2) 修改所有的vcxproj,sln文件，将Win32改成x64, -- 如果你的操作系统是64位的
3) 将所有的machine:X86 改成 machine:x64 -- 如果你的操作系统是64位的
4) 最后执行msbuild  ALL_BUILD.vcxproj /p:configuration=Release 生成 release版本的DLL

**Comment by seetafaceengine** [comment]
Pull newest version again. Try cmake this time. Read `README.md` for more detials.
