### ISSUE TITLE
FD face score?

### ISSUE THREAD

**Issue by yja1** [seetafaceengine/SeetaFace2#2]
when run example.cpp

for( SeetaFaceInfo &face : faces )
    {
        cout<< face.pos.x << " " << face.pos.y << " " << face.pos.width << " " << face.pos.height << " " << face.score << "\n";
    }

"face.score" is the confidence of detection?

but when test fddb:the score look like strange
2002/08/11/big/img_591
1
186 71 170 204 460.925
2002/08/26/big/img_265
2
288 60 105 126 43.0423
53 32 103 123 2.36952
@seetafaceengine

**Comment by seetafaceengine** [comment]
Yes.^_^
