### ISSUE TITLE
3288 armv7 Ubuntu16.04 无法编译

### ISSUE THREAD

**Issue by zouxiangxiang** [seetafaceengine/SeetaFace2#21]
3288 armv7 Ubuntu16.04 无法编译

**Comment by seetafaceengine** [comment]
It already fixed in [50b9760393d26156a282fb97e2a5ac91ffa9af45](https://github.com/seetafaceengine/SeetaFace2/commit/50b9760393d26156a282fb97e2a5ac91ffa9af45). Have a try again. ^_^.
