### ISSUE TITLE
为什么我的电脑上测试胡歌那张照片就要10s，我做错了那里

### ISSUE THREAD

**Issue by liuhuaer** [seetafaceengine/SeetaFace2#22]

**Comment by GangLiCN** [comment]
Where is your test  code ?

**Comment by liuhuaer** [comment]
> Where is your test code ?

在example文件夹下面

**Comment by seetafaceengine** [comment]
You may test the debug version. Try release again. Besides, You PC need powerful CPU greater than I7-6xxx to get the given performance.

**Comment by liuhuaer** [comment]
我用的i5-3470 3.2GHz  这和Readme的么中给出帧率差距也太大了，还有就是_mm_fmadd_ps这个指令在intel CPU下不是通用的吧，会报非法指令的错误，最后就是在windows下没有.so的文件，无法NDK编译

**Comment by seetafaceengine** [comment]
3代i5和6代i7的性能差异是必然的。CPU 优化涉及到了 SSE2 和 FMA 指令集。Android 的库需要编译，具体编译方式参照 README.md 中 Android 的部分。

**Comment by xiaomengxin114514** [comment]
原来如此，我说怎么要10s左右，开了相关指令集就只要5s左右了
