### ISSUE TITLE
Resnet50太慢，如何将自己训练的caffe模型转换到seetaface2的格式

### ISSUE THREAD

**Issue by tianxingyzxq** [seetafaceengine/SeetaFace2#23]
如题，有相应的转换工具没

**Comment by seetafaceengine** [comment]
感谢您的支持。当前代码不提供转换工具，更多支持可以联系商务邮箱`bd@seetatech.com`。

**Comment by zengjiechuan** [comment]
测试了一下，windows x64 debug 下提取一张图片（大小为112x112）特征要20s左右，是不是我操作有问题？？？

**Comment by zengjiechuan** [comment]
测试了一下，windows x64 debug 下提取一张图片（大小为112x112）特征要20s左右，是不是我操作有问题？？？
