### ISSUE TITLE
CMAKE + VS 2015 编译注意事项(严格按照这些步骤做,基本上100%成功)

### ISSUE THREAD

**Issue by GangLiCN** [seetafaceengine/SeetaFace2#25]
首先，我要说一句，这个项目的build 脚本 写的比较烂，可以说压根就没有在 Windows X64 平台测试过, 用Nmake 在windows平台编译肯定是失败的。

开源项目在开源前一定要做好跨平台的测试工作，否则发布出来了也是一堆乱七八糟的编译错误，让使用者对你这个项目的第一印象非常差 !!!

要想使用VS 2015 成功编译此代码， 你需要按照以下步骤做:
1) 安装一个MS VS2015 native build tools, 当然安装完整版本的VS 2015更好;
2) 安装 CMake (至少是3以上版本,我用的3.1.4)
3) 首先编译SeetaNet，然后编译FaceDector, FaceLandMarker, FaceRecognizer.
编译的步骤都是一样的，先执行CMake 生成VC的工程文件，然后执行msbuild 生成dll和lib

3.1 cmake .. -G"Visual Studio 14 2015 win64"
这里的Visual Studio 14 代表 VS 2015,  Visual Studio 15代表VS 2017, 以此类推。
win64是必须输入的，代表platform,不输入的话缺省值是win32, 在64位操作系统 执行build时
会出错。

3.2  
msbuild ALL_BUILD.vcxproj /p:configuration=Release --生成release版本的dll
msbuild ALL_BUILD.vcxproj /p:configuration=Debug --生成debug版本的dll

4. 如果你在源码编译过程中还遇到了其它错误, 只能具体问题具体分析, 一般来说
做到以下两步 基本就没问题了
4.1 修改所有的vcxproj, sln文件，将Win32改成x64, -- 如果你的操作系统是64位的
4.2 将所有的machine:X86 改成 machine:x64 -- 如果你的操作系统是64位的

**Comment by KangLin** [comment]
git pull 更新到最新的代码，按README.md中编译说明操作。

**Comment by GangLiCN** [comment]
编译源码只是第一步，更恐怖的还是运行例子程序

不是说好了没有第三方依赖么 ？ 使用opencv 是几个意思 ？  既然使用opencv 为什么不打包一个
opencv的二进制包 ？

**Comment by KangLin** [comment]
中国特色的社会主义：）
