### ISSUE TITLE
重复存入图片导致的问题

### ISSUE THREAD

**Issue by 2151330** [seetafaceengine/SeetaFace2#26]
将自己的图片存进注册列表时的具体步骤是什么呢，是不是我重复操作导致了这个问题，请问怎么清除注册列表的图片重新存入呢？
![image](https://user-images.githubusercontent.com/41284417/63327687-43e78080-c361-11e9-8d2a-cfb58b16f144.png)

**Comment by seetafaceengine** [comment]
try call FaceDatadase's API `Clear`.

**Comment by 2151330** [comment]
I downloaded your code again, as the original method in example/search， first make , but the error was reported, how to solve this problem?
![image](https://user-images.githubusercontent.com/41284417/63345345-27f5d600-c385-11e9-9259-95a66bb31fdf.png)

**Comment by seetafaceengine** [comment]
Use top folder's cmake file to compile example. Read "README.md" for more detial.
