### ISSUE TITLE
'Illegal instruction (core dumped)' when run example on ubuntu18.04 + x86-64 env

### ISSUE THREAD

**Issue by wmatrix** [seetafaceengine/SeetaFace2#28]
![seetaface-core-dumped](https://user-images.githubusercontent.com/6795531/63349538-3a284200-c38e-11e9-9def-2de5f1df1bab.png)

**Comment by liuhuaer** [comment]
可能是你的CPU不支持程序中的一些指令

**Comment by huanzhishuiyue** [comment]
16.04编译完后，执行提示Illegal instruction

**Comment by seetafaceengine** [comment]
Framework on x86 CPU need SEE2 and FMA support.

**Comment by wmatrix** [comment]
> 
> 
> Framework on x86 CPU need SEE2 and FMA support.

so how can i fix this problem,my notebook is AMD A6 cpu.

**Comment by qaz734913414** [comment]
win7上vs2015 x86编译也出现一样的问题，执行提示Illegal instruction

**Comment by seetafaceengine** [comment]
The newest version removed low compatibility `FMA` instructions. Update code and re-compile. The already fixed. Now, the lowest capability needed it `SSE2`.

**Comment by wmatrix** [comment]
> 
> 
> The newest version removed low compatibility `FMA` instructions. Update code and re-compile. The already fixed. Now, the lowest capability needed it `SSE2`.

the top CMakeLists.txt already set SEETA_USE_FMA option to OFF, but CMakeLists.txt in subdir SeetaNet still has "-mfma" compile option in x86/x64 platform, it still cause "Illegal instruction" problem when run example. maybe should add "-mfma" opiton only SEETA_USE_FMA is set to ON? @seetafaceengine
