### ISSUE TITLE
无法打开文件“SeetaFaceRecognizer2d.lib”

### ISSUE THREAD

**Issue by jiazhaozhu** [seetafaceengine/SeetaFace2#3]
无法打开文件“SeetaFaceRecognizer2d.lib”

**Comment by njvisionpower** [comment]
![image](https://user-images.githubusercontent.com/46888660/63245993-2d272800-c294-11e9-8f73-7a5b0c92b9ad.png)
你需要先编译lib，编译脚本在SeetaFace2-master\craft目录

**Comment by seetafaceengine** [comment]
call `/craft/windows/build.x64.debug.cmd` to build debug libraires ending with d.

**Comment by bayueyaoshao** [comment]
SeetaFace2-master目录下咋找不到craft目录啊，我是用的vs2017+opencv3.4.1也报了这个错误，不知道怎么解决
