### ISSUE TITLE
人脸关键点问题

### ISSUE THREAD

**Issue by Heroism502** [seetafaceengine/SeetaFace2#32]
请问下300W是68个人脸关键点，在计算定位误差时，你的81和5时怎么对应的？
五点坐标是直接合成眼睛和嘴巴关键点吗？81点坐标比68点多了哪些点，81点中的68点是不是和300w的一一对应的？

**Comment by seetafaceengine** [comment]
5 points are center of left eye, center of right eye, nose top, left mouth corner and right mouth corner. 81 points are shown as be following.
![81points](https://user-images.githubusercontent.com/53942815/63413284-fdab2380-c42b-11e9-8d75-35654019f00d.png)
