### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by lebronze** [seetafaceengine/SeetaFace2#34]
cmake --build  .失败，报了2个错误：
“D:\SeetaFace2-master2\build\ALL_BUILD.vcxproj"(默认目标)（1） ->
“D:\SeetaFace2-master2\build\Facedetector\SeetaFaceDetector.vcxproj"(默认目标)（3） ->
“D:\SeetaFace2-master2\build\SeetaNet\SeetaNet.vcxproj"(默认目标)（4） ->
(C1Compile 目标)->
D:\SeetaFace2-master2\SeetaNet\src\include_inner\SeetaNetSimd.h(775): error C2719:  "value" : 要求对齐 [D:\Seet
aFace2-master2\build\SeetaNet\SeetaNet.vcxproj]
D:\SeetaFace2-master2\SeetaNet\src\include_inner\SeetaNetSimd.h(847): error C2719:  "value" : 要求对齐 [D:\Seet
aFace2-master2\build\SeetaNet\SeetaNet.vcxproj]

这个是什么错呢？

**Comment by seetafaceengine** [comment]
It may fixed in newest version. `pull` them and try again.
