### ISSUE TITLE
Exception thrown when calling FL.mark() function.

### ISSUE THREAD

**Issue by lin1github** [seetafaceengine/SeetaFace2#37]
I would like to thank the authors for their times and efforts devoted to this open source project. I was in trouble when I attempted to extract features from two images and calculate their similarity. Here is my code :

![error2](https://user-images.githubusercontent.com/8955094/63478363-267af980-c4bc-11e9-8750-51951f0c0df7.PNG)

It ran normally on the first part to extract the features of "1.jpg", but threw a exception when ran to the statement "auto points2 = FL.mark(simage2, face2.pos);". Here is the exception message:

![err](https://user-images.githubusercontent.com/8955094/63478348-18c57400-c4bc-11e9-8dc0-fecc23a5f1a2.jpg)

I cannot figure it out what's wrong with my code.

**Comment by seetafaceengine** [comment]
There is problem if non face detected.
```
auto faces = FD.detect(simage);
auto &face = faces.data[0];
```
And this similary problem after `cv::imread` failed.
New float array need `[]` instead `()`. Change `new float(featureLen)` to `new float[featureLen]` and change `delete(features)` to `delete [] features`. `new float(featurelen)` only malloc 1 element of float contains `featurelen`.
Fix them and try agin. Have a good day! ^_^

**Comment by lin1github** [comment]
> There is problem if non face detected.
> 
> ```
> auto faces = FD.detect(simage);
> auto &face = faces.data[0];
> ```
> 
> And this similary problem after `cv::imread` failed.
> New float array need `[]` instead `()`. Change `new float(featureLen)` to `new float[featureLen]` and change `delete(features)` to `delete [] features`. `new float(featurelen)` only malloc 1 element of float contains `featurelen`.
> Fix them and try agin. Have a good day! ^_^

It works. So grateful for your reply.
