### ISSUE TITLE
1比N的人脸库有作持久化吗

### ISSUE THREAD

**Issue by huanzhishuiyue** [seetafaceengine/SeetaFace2#38]
如果有作持久化，持久化的文件在哪里，另外只看到注册的代码，没有看到有删除的

**Comment by seetafaceengine** [comment]
See `FaceDatabase.h` for more APIs like `Save`, `Load` and `Clear`.  Besides, you can use `FaceRecognizer.h` `Extract` or `ExtractCroppedFace` APIs to get the features of face. The features are  save as a vecotr of float, length 1024. It can be saved in any way you want.
Have a good day! ^_^.
