### ISSUE TITLE
error: ‘function’ in namespace ‘std’ does not name a template type

### ISSUE THREAD

**Issue by vicwer** [seetafaceengine/SeetaFace2#4]
Linux error:
pot.h:19:36: error: ‘function’ in namespace ‘std’ does not name a template type

cmake version 3.10.2, gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
c++11 ???

**Comment by seetafaceengine** [comment]
> 
> 
> Linux error:
> pot.h:19:36: error: ‘function’ in namespace ‘std’ does not name a template type
> 
> cmake version 3.10.2, gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
> c++11 ???

It may missing "#include ". Add to fix it.

**Comment by seetafaceengine** [comment]
It may missing "#include <functional>". Add to fix it.

**Comment by seetafaceengine** [comment]
It may missing "#include \<functional\>". Add to fix it.
