### ISSUE TITLE
The result generated by cmake does not have a bin folder

### ISSUE THREAD

**Issue by heshuting555** [seetafaceengine/SeetaFace2#44]
D:\VS2015\SeetaFace2-master\build>cd bin
系统找不到指定的路径。

I follow the readme step by step, but there is no bin folder in the final build folder.

I hope someone can help, I am very grateful.

**Comment by liwanning** [comment]
你编译的时候没有编译example，所以没build/bin

**Comment by heshuting555** [comment]
谢谢您的回复～感谢感谢


发自我的iPhone

------------------ Original ------------------
