### ISSUE TITLE
灰度图像无法识别

### ISSUE THREAD

**Issue by dhatbj** [seetafaceengine/SeetaFace2#46]
复现步骤：安卓平台，照相机采集数据输入，图片大小 640x360，NV21格式转成RGB24格式，可以识别出人脸；
   // byteArray 是 NV21格式图片数据
    jbyte* imgData = env->GetByteArrayElements(byteArray, 0);

    SeetaImageData imageData;
    imageData.width = width;
    imageData.height = height;
    imageData.channels = 3;
    imageData.data = (unsigned char*)NV21ToBGR888(width, height, (const uint8_t*)imgData);

    SeetaFaceInfoArray infoArray = faceDetector->detect(imageData);

    if (infoArray.size == 0) {
        LOGI("No face found");
        env->ReleaseByteArrayElements(byteArray, imgData, 0);
        free(imageData.data);
        return (jboolean)false;
    }

    LOGI("A face found”);

输出为：A face found

但如果直接使用灰度图输入，无法识别出人脸。
   // byteArray 是 NV21格式图片数据
    jbyte* imgData = env->GetByteArrayElements(byteArray, 0);

    SeetaImageData imageData;
    imageData.width = width;
    imageData.height = height;
    imageData.channels = 1;
    // NV21 头部为灰度图数据
    imageData.data = (unsigned char*)imgData;

    SeetaFaceInfoArray infoArray = faceDetector->detect(imageData);

    if (infoArray.size == 0) {
        LOGI("No face found");
        env->ReleaseByteArrayElements(byteArray, imgData, 0);
        return (jboolean)false;
    }

    LOGI("A face found”);

输出为 No face found

**Comment by seetafaceengine** [comment]
FaceDetector only support BGR format color image. You must input 3-channls image even if it's gray image.
