### ISSUE TITLE
我想把初始化之后的facelandmark模型参数传递给其他函数，请问我该怎么做？谢谢

### ISSUE THREAD

**Issue by cvJie** [seetafaceengine/SeetaFace2#47]
我想把初始化之后的facelandmark模型参数传递给其他函数，请问我该怎么做？
例如：	
        seeta::FaceLandmarker FL(FL_model);
   //将FL传递给下面这个函数，FL应该就是初始化之后的facelandmark模型参数
	getFacelandmark(FL, frame);

谢谢

**Comment by seetafaceengine** [comment]
Pass by reference. like
```
void getFaceLandmaker(const seeta::FaceLandmarker &FL, const SeetaImageData &image) {
    // ...
}
```
