### ISSUE TITLE
windows测试成功，感谢你们的工作。请问文档会提供训练的相关工作吗？

### ISSUE THREAD

**Issue by njvisionpower** [seetafaceengine/SeetaFace2#5]
检测部分比较快，初略看代码应该还是用的改良版的MTCNN，优化了网络结构和PNet的输入大小等。识别网络我看说明是用的ResNet50，有没有用类似于arcface之类的损失训练，或者做一些模型的改进？这部分比较耗时，初看没有insightface的r50跑的块（我实现的mxnet C++版本，开启MKL）。

**Comment by seetafaceengine** [comment]
感谢您的支持！暂时不会提供训练相关材料。

**Comment by Laulian** [comment]
@njvisionpower 你好，请问下windows+vs15+cmake， 运行编译脚本报错，是缺了什么编译工具么
