### ISSUE TITLE
SeetaFaceInfo:struct类型重定义/使用未定义类型SeetaFaceInfoArray

### ISSUE THREAD

**Issue by JasonChenhx** [seetafaceengine/SeetaFace2#51]
我是只需要FaceDetector和FaceLandMarker和SeetaNet，所以在vs2015中只引入了这三个文件的源文件，然后在附加包目录下添加所需要的头文件所在的文件，自己编写了一个test的源文件，就报出该错误。求解。感谢

**Comment by seetafaceengine** [comment]
应该是加入了同名源代码（包含了重复结构）导致了对象重定义。删除掉重名结构体或文件即可。
