### ISSUE TITLE
 Invalid setting of "seeta::ModelSetting::GPU"

### ISSUE THREAD

**Issue by XingyuZU** [seetafaceengine/SeetaFace2#56]
In SeetaFace2/example/search/example.cpp, line 16, I find the setting: 
`seeta::ModelSetting::Device device = seeta::ModelSetting::CPU;`
but when I change "CPU" to "GPU", nothing happened.
I have correctly install CUDA & CuDNN and used other DL frame like PyTorch.

**Comment by seetafaceengine** [comment]
Now release version is only support CPU inference. GPU setting is reserved option.
