### ISSUE TITLE
人脸检测框抖动的厉害，这个有什么好的方法来改善吗？

### ISSUE THREAD

**Issue by MirrorYuChen** [seetafaceengine/SeetaFace2#58]
如题，在测试seetaface人脸检测时，发现检测框会出现明显抖动现象，请问一下有什么方法来改善吗？

**Comment by qaz734913414** [comment]
FD.set(seeta::FaceDetector::PROPERTY_VIDEO_STABLE, 1);

**Comment by MirrorYuChen** [comment]
![image](https://user-images.githubusercontent.com/49817428/65028056-fcf3a780-d96d-11e9-92d3-dd3229ec5101.png)
好像已经设置了~

**Comment by filannn** [comment]
碰巧我做过类似的特征点稳定，或许把坐标滤波能好一些，因为本质上就是坐标值平滑嘛，参数需要自己调试一下。

**Comment by MirrorYuChen** [comment]
> 碰巧我做过类似的特征点稳定，或许把坐标滤波能好一些，因为本质上就是坐标值平滑嘛，参数需要自己调试一下。

坐标滤波指的是？大佬能具体说一下吗？

**Comment by filannn** [comment]
> > 碰巧我做过类似的特征点稳定，或许把坐标滤波能好一些，因为本质上就是坐标值平滑嘛，参数需要自己调试一下。
> 
> 坐标滤波指的是？大佬能具体说一下吗？

啊我不是大佬诶，只是碰巧做过类似的，就是对坐标值进行滤波，有一阶、二阶滤波等方法

**Comment by MirrorYuChen** [comment]
> > > 碰巧我做过类似的特征点稳定，或许把坐标滤波能好一些，因为本质上就是坐标值平滑嘛，参数需要自己调试一下。
> > 
> > 
> > 坐标滤波指的是？大佬能具体说一下吗？
> 
> 啊我不是大佬诶，只是碰巧做过类似的，就是对坐标值进行滤波，有一阶、二阶滤波等方法

能具体举例讲解一下吗？非常感谢！！！！

**Comment by filannn** [comment]
> > > > 碰巧我做过类似的特征点稳定，或许把坐标滤波能好一些，因为本质上就是坐标值平滑嘛，参数需要自己调试一下。
> > > 
> > > 
> > > 坐标滤波指的是？大佬能具体说一下吗？
> > 
> > 
> > 啊我不是大佬诶，只是碰巧做过类似的，就是对坐标值进行滤波，有一阶、二阶滤波等方法
> 
> 能具体举例讲解一下吗？非常感谢！！！！

不好意思啊，我很想和您讲明白这个，但是这个内容实在太多不好讲，您可以百度一下有关消抖滤波的资料，或许会有更大的收获呢。

**Comment by MirrorYuChen** [comment]
好滴好滴，万分感谢~

**Comment by qaz734913414** [comment]
好像看源码中人脸框做了坐标值平滑

**Comment by MirrorYuChen** [comment]
好的，感谢，我再研究一下，在这里也非常感谢seetaface团队优秀的开源project！
