### ISSUE TITLE
运行example报错

### ISSUE THREAD

**Issue by lmylmylmylmy** [seetafaceengine/SeetaFace2#59]
x86_64，Ubuntu16.04，运行example报错：非法指令（核心已转储）

**Comment by huanzhishuiyue** [comment]
如果在虚拟机运行我遇到了这个问题，换成物理机就可以了

**Comment by KangLin** [comment]
由于CMakeLists.txt中没有移除FMA指令，所以出错。已在 Support cmake build for android and modify some bug #66 中修改。还没有合并到主分支，你可以用：https://github.com/KangLin/SeetaFace2/tree/develop
