### ISSUE TITLE
树莓派编译找不到immintrin.h

### ISSUE THREAD

**Issue by filannn** [seetafaceengine/SeetaFace2#60]
![image](https://user-images.githubusercontent.com/46132474/65137282-a2288180-da3b-11e9-9ba8-38692c39b53c.png)
平台是选择的arm，但是编译的时候出现了找不到immintrin.h这个错误，想问一下大神们应该怎么去解决这个问题。

**Comment by kakaluote** [comment]
同问

**Comment by wetwoo** [comment]
添加宏定义：
-D__ARM_NEON
-D__ARM_NEON__

**Comment by filannn** [comment]
> 添加宏定义：
> -D__ARM_NEON
> -D__ARM_NEON_
感谢大神的指点，get了

**Comment by filannn** [comment]
![image](https://user-images.githubusercontent.com/46132474/65559737-70994400-df6e-11e9-9255-8c01ef4588e8.png)
也遇到这个问题的朋友看这段代码
