### ISSUE TITLE
ARM平台编译报错

### ISSUE THREAD

**Issue by aheng365** [seetafaceengine/SeetaFace2#61]
使用的gcc为：arm-poky-linux-gnueabi-gcc 4.9.1 报错如下：
/SeetaFace2-master/SeetaNet/src/orz/sync/../tools/ctxmgr_lite_support.h: In static member function 'static void* seeta::orz::__thread_local_lite_context<T>::swap(seeta::orz::__thread_local_lite_context<T>::context)':
/SeetaFace2-master/SeetaNet/src/orz/sync/../tools/ctxmgr_lite_support.h:25:28: internal compiler error: in var_defined_without_dynamic_init, at cp/decl2.c:3005
             auto pre_ctx = m_ctx;
                            ^
Please submit a full bug report,
with preprocessed source if appropriate.

**Comment by seetafaceengine** [comment]
已知的情况是编译器的C++11不完全支持的bug。尝试升级到5.x以上版本GCC后编译。
