### ISSUE TITLE
人脸检测的得分范围

### ISSUE THREAD

**Issue by ZhangWen0301** [seetafaceengine/SeetaFace2#64]
测试了一下，人脸检测输出的得分很奇怪，473.03662109375， 43.56840515136719，129.0093994140625，7.850157260894775？请问得分的范围是多少

**Comment by seetafaceengine** [comment]
人脸得分即`SeetaFaceInfo::score`的得分数据为[0, 1]。

**Comment by GuiBin2013** [comment]
@seetafaceengine 
我也得到奇怪的分数，甚至上万的分数都有...
我的代码也只是简单的detectFaces = FD->detect(image); 

@ZhangWen0301 
请问你解决了吗？

**Comment by opentld** [comment]
> 人脸得分即`SeetaFaceInfo::score`的得分数据为[0, 1]。

很显然你应该是忘记归一化了吧？我的得分也是好几百~~~
哦，对了，我是直接调用的SEETA_API SeetaFaceInfoArray detect( const SeetaImageData &image ) const;这个函数！
@seetafaceengine
