### ISSUE TITLE
android编译完成之后，如何使用呢？

### ISSUE THREAD

**Issue by geeeeeeeek** [seetafaceengine/SeetaFace2#67]
编译成so之后，如何使用？调用哪个方法？

**Comment by seetafaceengine** [comment]
需要通过JNI方式调用，参考[https://github.com/xiaoxiaoazhang/SeetaFace2AndroidDemo](https://github.com/xiaoxiaoazhang/SeetaFace2AndroidDemo)。

**Comment by Kylewwb** [comment]
> 编译成so之后，如何使用？调用哪个方法？

你好，能发一下arm64-v8a 的so文件吗？
