### ISSUE TITLE
人脸旋转角度后对齐结果很差

### ISSUE THREAD

**Issue by GuiBin2013** [seetafaceengine/SeetaFace2#69]
输入了几张旋转过后的图片(人脸和水平线呈一定角度)进行对齐
发现输出的对齐图片和未旋转输出的对齐图片差别很大？
请问是算法本算不支持大于一定角度(约左右45)的人脸对齐或者需要对图片进行处理，又或者？

**Comment by seetafaceengine** [comment]
![1 jpg crop](https://user-images.githubusercontent.com/53942815/66824911-c8c6d300-ef7b-11e9-9240-cbe391b160e1.png)
如果使用FaceRecognzier::CropFace对齐人脸的话，如果定位点正确的话，对齐结果如上图（256x256）。**注意**：这个接口只能输入5点进行用于人脸识别的对齐。
如果对齐结果不是如图所示，往往是由于特征点定位失败（不准）造成的，这个就属于精度外的情况了。
如果需要多个特征点进行通用的图像对齐操作，请参考[ImageProcess.h](https://github.com/seetafaceengine/SeetaFace2/blob/master/FaceRecognizer/seeta/ImageProcess.h)或者[common_alignment.h](https://github.com/seetafaceengine/SeetaFace2/blob/master/FaceRecognizer/seeta/common_alignment.h)的实现。
