### ISSUE TITLE
detail compile steps needed

### ISSUE THREAD

**Issue by ggsonic** [seetafaceengine/SeetaFace2#7]
in ubuntu 18.04, compile not work. tried many methods. can you give a detailed steps about compiling?

**Comment by seetafaceengine** [comment]
See the `craft/linux/build.linux.x64.sh` for detials. Briefly speaking, compile `SeetaNet` firstly, then compile `FaceDetector`, `FaceLandmarker` and `FaceRecognizer`.

**Comment by ggsonic** [comment]
OK, i can compile now, Thank you!
