### ISSUE TITLE
请问在ARM、UBUNTU 18.04系统中编译时的配置？

### ISSUE THREAD

**Issue by git12137** [seetafaceengine/SeetaFace2#73]
编译时使用了`-DPLATFORM=arm`，但是仍然报错。提示如下：

`
root@cqh6:/home/qihua/test/SeetaFace2/build#cmake --build . --config Release

Scanning dependencies of target SeetaNet
[  2%] Building CXX object SeetaNet/CMakeFiles/SeetaNet.dir/src/ReadFromSeetaNetLayer.cpp.o
c++: error: unrecognized command line option ‘-msse2’
SeetaNet/CMakeFiles/SeetaNet.dir/build.make:62: recipe for target 'SeetaNet/CMakeFiles/SeetaNet.dir/src/ReadFromSeetaNetLayer.cpp.o' failed
make[2]: *** [SeetaNet/CMakeFiles/SeetaNet.dir/src/ReadFromSeetaNetLayer.cpp.o] Error 1
CMakeFiles/Makefile2:117: recipe for target 'SeetaNet/CMakeFiles/SeetaNet.dir/all' failed
make[1]: *** [SeetaNet/CMakeFiles/SeetaNet.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

在头文件里直接定义`#define  __ARM_NEON__`错误提示也一样。
GCC的版本是：`gcc (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0`。

**Comment by KangLin** [comment]
Update code from https://github.com/KangLin/SeetaFace2/commit/784752e739ad2f11b3a6246ebb6db242d445a331
use -DSEETA_USE_SSE2=OFF close the sse2
see #76
