### ISSUE TITLE
print too much

### ISSUE THREAD

**Issue by yangtianyu92** [seetafaceengine/SeetaFace2#79]
打印那么多干啥啊，我个人想看的看不着。怎么控制一下。

**Comment by seetafaceengine** [comment]
你可能用的是debug版本，打印的调试信息。用release试一下^_^。

**Comment by yangtianyu92** [comment]
> 你可能用的是debug版本，打印的调试信息。用release试一下^_^。

但是我用的就是release版本下的81点例子。它也打印了一整页。。。我再重新编译下看看

**Comment by seetafaceengine** [comment]
> 
> 
> > 你可能用的是debug版本，打印的调试信息。用release试一下^_^。
> 
> 但是我用的就是release版本下的81点例子。它也打印了一整页。。。我再重新编译下看看

同步最新的develop分支，看能否解决你的疑问^_^。
