### ISSUE TITLE
人脸数据库是存在内存中的吗？

### ISSUE THREAD

**Issue by luofei614** [seetafaceengine/SeetaFace2#87]
请问， 源码中人脸数据库 FDB 是一个内存数据库吗？  怎么存成持久化的数据？

**Comment by yutao007** [comment]
应该是在内存中了，除非自己增加数据库链接

**Comment by seetafaceengine** [comment]
存放在内存中的。是`std::map<int64_t, std::shared_ptr<float>>`对象[FaceDatabase.cpp:303](https://github.com/seetafaceengine/SeetaFace2/blob/88b31409d12c8cee4476f90d3f0eb8cd9fba5d01/FaceRecognizer/src/seeta/FaceDatabase.cpp#L303)。
