### ISSUE TITLE
在example/search目录下执行make报如下错： ./seeta/Struct_cv.h:3:33: fatal error: opencv2/core/core.hpp: No such file or directory compilation terminated. Makefile:22: recipe for target 'example.o' failed make: *** [example.o] Error 1

### ISSUE THREAD

**Issue by qingfengmingyue** [seetafaceengine/SeetaFace2#9]
在example/search目录下执行make报如下错：
./seeta/Struct_cv.h:3:33: fatal error: opencv2/core/core.hpp: No such file or directory
compilation terminated.
Makefile:22: recipe for target 'example.o' failed
make: *** [example.o] Error 1

**Comment by seetafaceengine** [comment]
You need install opencv firstly. Simply like, `sudo apt-get install libopencv-dev`

**Comment by qingfengmingyue** [comment]
/usr/bin/ld: cannot find -lopencv_imgcodecs
/usr/bin/ld: cannot find -lopencv_videoio
collect2: error: ld returned 1 exit status
Makefile:15: recipe for target 'search' failed
make: *** [search] Error 1

**Comment by jhb86253817** [comment]
you can remove the -lopencv_imgcodecs and -lopencv_videoio in Makefile if you don't use OpenCV3

**Comment by seetafaceengine** [comment]
Pull newest version again. Try cmake this time. Read README.md for more detials. Cmake will detect your env OpenCV.
