### ISSUE TITLE
CropFace函数截取的不是人脸

### ISSUE THREAD

**Issue by cx1628555321** [seetafaceengine/SeetaFace2#95]
更改demo代码如下

int test_image2(seeta::FaceDetector *FD, seeta::FaceLandmarker *FL, seeta::FaceRecognizer *FR)
{
	std::string image_path = "../../Bin64/1.jpg";
	std::cout << "Loading image: " << image_path << std::endl;
	auto frame = cv::imread(image_path);
	seeta::cv::ImageData simage = frame;
	if (simage.empty()) {
		std::cerr << "Can not open image: " << image_path << std::endl;
		return EXIT_FAILURE;
	}

	
	auto faces = FD->detect(simage);

	auto frameDraw = frame.clone();
	
	for (int i = 0; i < faces.size; ++i)
	{
		auto &face = faces.data[i];
		cv::rectangle(frameDraw, cv::Rect(face.pos.x, face.pos.y, face.pos.width, face.pos.height), CV_RGB(128, 128, 255), 3);
		//auto points = FL->mark(simage, face.pos);
		//for (auto &point : points)
		//{
		//	//std::cerr << point.x<<" "<<point.y  << std::endl;
		//	cv::circle(frameDraw, cv::Point(point.x, point.y), 3, CV_RGB(128, 255, 128), -1);
		//}
	}

	SeetaRect faceRect = faces.data[0].pos;
	SeetaPointF *PointsTmp = (SeetaPointF *)malloc(sizeof(SeetaPointF)*81);
	FL->mark(simage, faceRect, PointsTmp);
	for (int i = 0; i < 2;i++)
	{
		//std::cerr << point.x<<" "<<point.y  << std::endl;
		cv::circle(frameDraw, cv::Point(PointsTmp[i].x, PointsTmp[i].y), 3, CV_RGB(128, 255, 128), -1);
	}
	int CropW = FR->GetCropFaceWidth();
	int CropH = FR->GetCropFaceHeight();
	int CropC = FR->GetCropFaceChannels();
	std::cerr <<CropW<<" "<<CropW<<" "<<CropC<< std::endl;
	seeta::cv::ImageData CropFaceDate(CropW, CropH, CropC);
	//SeetaPointF *PointCrop = (SeetaPointF *)malloc(sizeof(SeetaPointF));
	//PointCrop->x = 594;
	//PointCrop->y = 477;
	bool isOK = FR->CropFace(simage, PointsTmp, CropFaceDate);
	free(PointsTmp);
	cv::Mat CropFaceMat = CropFaceDate.toMat();
	cv::imshow("Crop", CropFaceMat);
	cv::imshow("asdf", frameDraw);
	cv::waitKey(0);

![image](https://user-images.githubusercontent.com/29647085/70601142-63662a00-1c2c-11ea-89f8-2fe1fe26db19.png)

**Comment by seetafaceengine** [comment]
需要使用5点定位输入CropFace，不可以使用81点。
