### ISSUE TITLE
识别不准确的

### ISSUE THREAD

**Issue by jingruhou** [seetafaceengine/SeetaFace2#97]
检测的精度和速度还是挺快的，但是识别的精度差的太远了。有没有相关对齐的模型或者源码参考一下呢？

**Comment by seetafaceengine** [comment]
[FaceRecognizerPrivate.cpp:369](https://github.com/seetafaceengine/SeetaFace2/blob/88b31409d12c8cee4476f90d3f0eb8cd9fba5d01/FaceRecognizer/seeta/FaceRecognizerPrivate.cpp#L369)
